=== Saxonica/XT-Speedo/data/docbook-tests/docbook/xsl/com.oxygenxml.webhelp/oxygen-webhelp/resources/localization/strings.dtd
<!--

Oxygen Webhelp plugin
Copyright (c) 1998-2013 Syncro Soft SRL, Romania.  All rights reserved.
Licensed under the terms stated in the license file EULA_Webhelp.txt 
available in the base directory of this Oxygen Webhelp plugin.

-->

<!ELEMENT strings (str)+>
<!ATTLIST strings xml:lang CDATA #REQUIRED>
<!ELEMENT str (#PCDATA)>
<!ATTLIST str name CDATA #REQUIRED>
<!ATTLIST str js (true|false) 'true'>
<!ATTLIST str php (true|false) 'false'>

=== Saxonica/XT-Speedo/data/docbook-tests/docbook/xsl/com.oxygenxml.webhelp/oxygen-webhelp/resources/localization/strings-en-us.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE strings SYSTEM "strings.dtd">
<!--

Oxygen Webhelp plugin
Copyright (c) 1998-2013 Syncro Soft SRL, Romania.  All rights reserved.
Licensed under the terms stated in the license file EULA_Webhelp.txt 
available in the base directory of this Oxygen Webhelp plugin.

-->

<!-- Translation strings for US English language. -->
<strings xml:lang="en-us">    
	  <str name="label.shareFrom">If you already have an user account for any of the following products, you can use that account to login.</str>
    <str name="label.unconfirmedUsers">Unconfirmed Users</str>
    <str name="label.cleanUsers">Clean Users</str>
    <str name="label.tc.userName">User</str>
    <str name="label.tc.name">Name</str>
    <str name="label.tc.email">E-mail</str>
    <str name="label.invertSel">Invert Selection</str>
    <str name="label.invalidPosts">Invalid pages for posts</str>
    <str name="label.cleanComments">Clean Comments</str>
    <str name="label.fbUnavailable">The feedback system is disabled! Please contact the WebHelp
        system administrator.</str>
    <str name="label.removeInst">The folder containing the installation scripts must be removed
        after the installation is complete!</str>
    <str name="label.plsRemoveInstall">Please contact system administrator to finalize the webhelp
        installation by removing the installation folder!</str>
    <str name="configInvalid">Invalid config File - run install first!</str>
    <str name="Content">Content</str>
    <str name="oldFrames">With Frames</str>
    <str name="Search">Search</str>
    <str name="Index">Index</str>
    <str name="Keywords">Keywords</str>
    <str name="Loading, please wait ...">Loading, please wait ...</str>
    <str name="Search no results">Your search returned no results for</str>
    <str name="Results for:">Results for:</str>
    <str name="There is no page containing all the search terms.">There is no page containing all
        the search terms.</str>
    <str name="Partial results:">Partial results:</str>
    <str name="Output generated by">WebHelp output generated by</str>
    <str name="You must enter at least one character.">You must enter at least one character.</str>
    <str name="Only first 10 words will be processed.">Only first 10 words will be processed.</str>
    <str name="Your browser is not supported. Use of Mozilla Firefox is recommended.">Your browser
        is not supported. Use of Mozilla Firefox is recommended.</str>
    <str name="linkToThis">Link to this page</str>
    <str name="ExpandAll">Expand All Topics</str>
    <str name="printThisPage">Print this page</str>
    <str name="CollapseAll">Collapse All Topics</str>
    <!-- comments -->
    <str name="label.currentPwd">Current Password</str>
    <str name="label.Unsaved">You have unsaved data</str>
    <str name="label.captcha">Enter the captcha code seen below:</str>
    <str name="label.welcome">Welcome</str>
    <str name="label.close">Close</str>
    <str name="label.cancel">Cancel</str>
    <str name="label.logAdmin">Log in as 'Moderator' user</str>
    <str name="label.guest">Guest</str>
    <str name="label.admin">Administrator</str>
    <str name="label.admin.title">Administrative Page</str>
    <str name="label.moderator">Moderator</str>
    <str name="label.user">User</str>
    <str name="label.userProfile" php="true">User Profile</str>
    <str name="label.yourName">Your Name</str>
    <str name="label.yourEmail">Your email address</str>
    <str name="label.IwantEmail">I want to receive an email when</str>
    <str name="label.commentPage">a comment is left on a page that I commented on</str>
    <str name="label.commentTopic">a comment is left on any topic in the Help system</str>
    <str name="label.commentMy">a reply is left to one of my comments</str>
    <str name="label.apply">Apply Changes</str>
    <str name="label.newPwd">New Password</str>
    <str name="label.reNewPwd">Retype New Password</str>
    <str name="label.chPwd">Change Password</str>
    <str name="label.comments">Comments</str>
    <str name="label.login">Log in</str>
    <str name="label.signUp">Sign Up</str>
    <str name="label.edit">Edit</str>
    <str name="label.logOff">Log Off</str>
    <str name="label.approveAll">Approve All</str>
    <str name="label.yes">Yes</str>
    <str name="label.no">No</str>
    <str name="label.addNewCmt">Add New Comment</str>
    <str name="label.plsWait">Please Wait ...</str>
    <str name="label.plsWaitChProfile">Loading User Profile ...</str>
    <str name="label.plsWaitRecover">Recovering Password ...</str>
    <str name="label.plsWaitSignUp">Signing you up ...</str>
    <str name="label.plsWaitUpProfile">Updating Your Profile ...</str>
    <str name="label.plsWaitUpPaswd">Updating your Password ... </str>
    <str name="label.plsWaitCmts">Loading Comments ... </str>
    <str name="label.plsWaitAuth">Verifying User ... </str>
    <str name="label.insertCmt">Insert Comment</str>
    <str name="label.submit">Submit</str>
    <str name="label.userName">User name</str>
    <str name="label.pswd">Password</str>
    <str name="label.lostPswd">Lost Password</str>
    <str name="label.signUp_userName">Choose a user name</str>
    <str name="label.signUp_email">Your Email Address</str>
    <str name="label.signUp_name">Your Name</str>
    <str name="label.signUp_password">Password</str>
    <str name="label.signUp_rPassword">Retype Password</str>
    <str name="label.recoverPwd">Reset Password</str>
    <str name="label.recoverEmail">Your Email Address</str>
    <str name="label.recoverUser">Your User Name</str>
    <str name="label.bt_recover" php="true">Reset Password</str>
    <str name="label.question">Are you sure you want to delete this message?</str>
    <str name="label.adminPanel">Admin Panel</str>
    <str name="label.changesNotApplied">Changes were not applied!</str>
    <str name="label.search.user">Search User Information</str>
    <str name="label.editUser">Edit User</str>
    <str name="label.updateUser">Update User</str>
    <str name="label.created">Created</str>
    <str name="label.validated">Validated</str>
    <str name="label.suspendend">Suspended</str>
    <str name="label.back">Back</str>
    <str name="label.setVersion">Set Version</str>
    <str name="label.export">Export Comments</str>
    <str name="label.confirm.bt">Confirm</str>
    <str name="label.selection">Selected Product / Version</str>
    <str name="label.version">Comments Version</str>
    <str name="label.versionInfo">The comments are visible starting from version: </str>
    <str name="label.rememberme">Remember me on this computer</str>
    <str name="label.viewAllPosts">View All Posts</str>
    <str name="label.allPosts">All Posts</str>
    <str name="label.forView">Select Product and Version to View Comments</str>
    <str name="label.forExport">Select Product and Version to Export Comments</str>
    <str name="label.product">Product</str>
    <str name="label.confirmGo">OK</str>
    <str name="delete" php="true">Delete</str>
    <!-- message form check user opperation -->
    <str name="checkUser.1">Anonymous user does not validate please contact system
        administrator!</str>
    <!-- the next three messages are not implemented yet-->
    <str name="checkUser.2"/>
    <str name="checkUser.3"/>
    <str name="checkUser.4"/>
    <str name="checkUser.loginError">Log in fail!</str>
    <str name="info.noComments" php="true">There are no comments!</str>
    <!--  when the system is allowing anonymous posts -->
    <str name="invalidCode">Please insert the specified captcha code</str>
    <str name="pwd.invalid">Invalid password</str>
    <str name="pwd.repeat">Please insert the same password!</str>
    <str name="pwd.empty">Please insert a minimum 5 characters password!</str>

    <str name="checkEmail-signUp">Please check your e-mail and validate your registration!</str>
    <str name="checkEmail-recover">Please check your e-mail for recovered password!</str>

    <str name="recoveryConfirmation">Your new password has been generated, please check your e-mail </str>

    <str name="editPost">Edit Comment</str>
    <str name="newPost">Insert Comment</str>

    <str name="admin">Administrator</str>
    <str name="moderator">Moderator</str>
    <str name="user">User</str>
    <str name="created">Created</str>
    <str name="validated">Validated</str>
    <str name="suspended">Suspended</str>

    <str name="label.back">Back</str>
    <str name="label.admin">Admin</str>
    <str name="label.adminComments">Comments</str>
    <str name="label.adminUsers">Users</str>
    <str name="logAdmin">Please authenticate with moderator credentials!</str>
    <str name="approveAllConfirmation">Approve all comments?</str>

    <str name="signUp.confirmOk" php="true">Confirmation successful!</str>
    <str name="signUp.invalidPswd" php="true">Invalid password supplied !</str>
    <str name="signUp.confirmUsr" php="true">User creation was successful confirmed!</str>
    <str name="signUp.invalidUsr" php="true">Invalid user specified to be confirmed!</str>
    <str name="signUp.userConfirmed" php="true">Your user has been already confirmed!</str>

    <str name="signUp.err.0">User creation has succeeded!</str>
    <str name="signUp.err.1">Password is too short!</str>
    <str name="signUp.err.2">Password contain invalid characters!</str>
    <str name="signUp.err.3">Invalid e-mail address!</str>
    <str name="signUp.err.4">User name is already taken!</str>
    <str name="signUp.err.5">Email is already in the database!</str>
    <str name="signUp.err.6">Please insert a valid user name!</str>
    <str name="signUp.err.6.info">User name must contain only alphanumeric characters without spaces
        and it must be at least 5 character long</str>
    <str name="signUp.err.9">Invalid Sign Up data!</str>
    <str name="signUp.err.10">User can not be created!</str>

    <!-- comments php -->
